packages = ["ddrescue", "extundelete", "ext4magic", "partclone", "partimage", "chntpw", "foremost", "libeatmydata", "efibootmgr", "efitools", "refind", "testdisk", "arch-install-scripts"]
aur_packages = ["hfsprogs", "hfsprescue-bin"]
